@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

Class ChillFlix{
-TextUI ui
-FileIO io
-String userPath
-String mediaPath
-List<User> userList
-List<IMedia> mediaList
+ChillFlix(String userPath, String mediaPath);
+boolean createUser();
+deleteUser();
+checkIfUserExists();
+search();
}

Class FileIO{
-Scanner scan
+readUserData();
+readMediaData();
+saveUserData();
+saveMediaData();
}

Class TextUI{
-Scanner scan
+promptChoice();
+promptNumeric();
+promptBinary();
+displayMsg();
+displayList();

}


Class User{
-String userName
-String userPassword
-List<IMedia> favorites
-List<IMedia> history
+User(String name, String password);
+userLogin();
+resetPassword();
+changePassword();
+changeUserName();
+displayFavorites();
+displayHistory();
+addFavorite();
+removeFavorite();
+addHistory();
+resetHistory();
+showSettings();
}

Interface IMedia{
+play();
+stop();
+pause();
+restart();
+skipIntro();
+playPrevious();
+playNext();
}
abstract Class Media{
-String title
-int releaseYear
-String genre
-float rating
+getTitle();
+getReleaseYear();
+getGenre();
+getRating();
+setTitle();
+setReleaseYear();
+setGenre();
+setRating();
}

Class Film {
-int duration
}

Class Serie{
-List<Season> seasonList
}
Class Season{
-List<IMedia> episodeList
}

Class Episode{
-int episodeNumber
-IMedia previousEpisode
-IMedia nextEpisode
}

Film <|-- Episode
Media <|-- Film
Media <|-- Serie
Media <|-- Season
IMedia <|.. Media
ChillFlix *- User
ChillFlix *-- IMedia
ChillFlix *-- FileIO
ChillFlix *-- TextUI
Main -- ChillFlix
User o- IMedia

@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--