@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

Class Main{
+static void main(String[] args)
}

Class ChillFlix{
-TextUI ui
-FileIO io
-String userPath
-String mediaPath
-HashMap<String, User> userList
-TreeMap<String, Media> mediaList
-User currentUser
+ChillFlix(String userPath, String mediaPath);
+boolean createUser();
+boolean loginDialog();
+deleteUser();
+checkIfUserExists();
+createUserDialog(String username);
+search();
+parseMovieData()
+createMovieFromString
+searchDialog()
}


Class User{
-String userName
-String userPassword
-LinkedHashMap<String, Media> favorites
-LinkedHashMap<String, Media> history
+User(String name, String password);
+userLogin();
+checkPassword(String pwd);
+resetPassword();
+changePassword();
+changeUserName();
+displayFavorites();
+displayHistory();
+addFavorite();
+removeFavorite();
+addHistory();
+resetHistory();
+showSettings();
+equals()
+hashCode()
}

Interface IMedia{
+play();
+stop();
+pause();
+restart();
+skipIntro();
+playPrevious();
+playNext();
}
abstract Class Media{
-String title
-int releaseYear
-String genre
-float rating
+getTitle();
+getReleaseYear();
+getGenre();
+getRating();
+setTitle();
+setReleaseYear();
+setGenre();
+setRating();
+equals()
+hashCode()
+compareTo()
}

Class Film {
-int duration
}

Class Serie{
-TreeMap<String,List<Media>> episodeMap
}


Class Episode{
-int episodeNumber
-Media previousEpisode
-Media nextEpisode
}
package util {
    Class FileIO{
    -Scanner scan
    +ArrayList<> scanFile();
    +readUserData();
    +readMediaData();
    +saveData(String header,ArrayList<Object> dataList, String path);
    }

    Class TextUI{
    -Scanner scan
    +void displayMsg(String msg);
    +void displayList(List<String> list);
    +void displayMedia(List<Media> mediaList, int start);
    +String promptText(String s);
    +String promptNumeric(String s, int maxValue);
    +boolean promptBinary(String input, String accept, String reject);
    +int promptChoice(List<String> inputList, String s);
    }
}

Film <|-- Episode
Media <|-- Film
Media <|-- Serie
Serie o-- Episode
IMedia <|.. Media
ChillFlix *- User
ChillFlix *-- IMedia
ChillFlix *-- FileIO
ChillFlix *-- TextUI
Main -- ChillFlix
User o- IMedia

@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <--