@startuml
'https://plantuml.com/sequence-diagram

title Skitse over programmets flow

Main -> ChillFlix
ChillFlix -> Movie : load film data
ChillFlix -> Serie : load serie data
ChillFlix -> User : load bruger data

alt opret bruger eller login
ChillFlix -> User : login
else
ChillFlix -> User : opret bruger
end

alt hovedmenu handlinger
ChillFlix -> ChillFlix : Vis kategori
ChillFlix -> UI : Vælg et medie fra kategorilisten
else
ChillFlix -> ChillFlix : Vis favoritter
ChillFlix -> UI : Vælg et medie fra listen
else
ChillFlix -> ChillFlix : Vis historik
ChillFlix -> UI : Vælg et medie fra listen
else
ChillFlix -> ChillFlix : Søg
ChillFlix -> UI : Vælg et medie fra resultatlisten
else
ChillFlix -> ChillFlix : Settings menu
end



@enduml