@startuml
'https://plantuml.com/sequence-diagram
title selectMovieDialog(Map<String,Media>mediaMap)
autonumber

participant ChillFlix
participant UI
participant Media

loop (!mediaMap.isEmpty())
ChillFlix -> ChillFlix : titleList = ArrayList(mediaMap.keySet())
ChillFlix -> UI: promptChoice(titleList,"Vælg fra listen")
UI --> ChillFlix: choice

alt choice < titleList.size()
ChillFlix -> Media: mediaMap.get(titleList.get(choice - 1))
Media --> ChillFlix: chosenMedia
alt Chosen media is a Serie
    ChillFlix -> ChillFlix: serieDialog(chosenMedia)

else Chosen media is not a Serie
    ChillFlix -> ChillFlix: mediaDialog(chosenMedia)
end
end
end

@enduml