@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ChillFlix
participant UI
participant User

loop
ChillFlix -> UI: promptText("Indtast brugernavn")
ChillFlix -> UI: promptText("Indtast kodeord")
loop
ChillFlix -> User: checkIfUserExists("username", "userPassword")
User --> ChillFlix: true/false
ChillFlix -> User: checkPassword("password")
User --> ChillFlix: true/false
ChillFlix <-- UI: displayMsg("brugernavn/kodeord kombination eksisterer ikke")
end
ChillFlix -> User: currentUser = userList.get(username)
ChillFlix <-- User: currentUser
end
ChillFlix --> ChillFlix: return true


@enduml
