@startuml
'https://plantuml.com/sequence-diagram
title mainDialog();

autonumber

loop while (proceed)
ChillFlix -> UI: ui.promptChoice(list, "Vælg en handling")

alt case 1: Vis Kategori
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Kategorier"
ChillFlix -> ChillFlix: selectGenreDialog
end

alt case 2: Vis favoritliste
alt if currentUser.getFavorites().isEmpty()
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Favoritlisten er tom"
else !isEmpty()
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Din favoritliste"
ChillFlix -> ChillFlix: selectMovieDialog(currentUser.getFavorites());
end

alt case 3: Vis historik
alt if currentUser.getHistory().isEmpty()
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Historik er tom"
else !isEmpty()
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Din historik"
ChillFlix -> ChillFlix: selectMovieDialog(currentUser.getHistory())
end

alt case 4: Søg efter titel
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Søg efter titel"
ChillFlix -> ChillFlix: searchDialog();
end

alt case 5: Settings
ChillFlix -> UI: displayMsg(msg)
UI --> ChillFlix: "Indstillinger"
end

alt case 6: Log ud
end

end
@enduml