@startuml
'https://plantuml.com/sequence-diagram
title genreDialog


participant ChillFlix
participant TextUI as ui
participant io
ChillFlix -> ChillFlix: genreList = new ArrayList(genreMap.keySet())
loop
alt !genreList.isEmpty
ChillFlix -> ui : promptChoice("Vælg en genre fra listen")
ui -> ui : displayList()
ui -> ui : promptNumeric()
ui --> ChillFlix
alt choice<listSize
ChillFlix -> ChillFlix : selectMovieDialog (genreMap.get(chosenGenre))
end
else
ChillFlix -> ui : displayMsg("Der er ingen genredata i systemet")
ui --> ChillFlix
end
@enduml